apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp 
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp 
        image: ikaksdevops.azurecr.io/webapp
        env:
        - name: APP_ENVIRONMENT
          value: "QA"
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regsecret
---
apiVersion: v1
kind: Service
metadata:
    name: websvc
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
      app: webapp