# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  kubernetesServiceConnection: '_update_here_'
  imageRepository: 'webapp'
  containerRegistry: '_update_here_'
  tag: 'latest'
  imagePullSecret: 'regsecret'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Deploy
  displayName: Deploy stage
  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    # create an environment (aks-qa) before run this pipeline
    environment: 'aks-qa'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: '_update_here_'
              definition: '_update_here_'
              buildVersionToDownload: 'latest'
              artifactName: 'manifests'
              targetPath: '$(Pipeline.Workspace)/manifests'
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              action: deploy
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              namespace: 'qa'
              manifests: |
                $(Pipeline.Workspace)/manifests/deployment_all.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)

